spring:
  application:
    name: order-service
    
  rabbitmq:
    host: 192.168.246.130
    port: 15672
    username: admin
    password: admin
  
    
server:
  port: 8201
  
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      
#开启熔断
feign:
  hystrix:
    enabled: true
      
#暴露端口
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
#负载均衡  
---
spring:
  profiles: order1
  
server:
  port: 8201
  
---
spring:
  profiles: order2
  
server:
  port: 8202


