spring:
  application:
    name: turbin
    
  rabbitmq:
    host: 192.168.246.130
    port: 5672
    username: wenwen
    password: wenwen
  
    
    
server:
  port: 5001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
turbine:
  app-config: order-service, feign
  cluster-name-expression: new String("default")

